# Generated by Django 5.2.1 on 2025-05-29 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_studymaterial_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordedclass",
            name="skill",
            field=models.CharField(
                blank=True,
                choices=[
                    ("speaking", "Speaking"),
                    ("listening", "Listening"),
                    ("reading", "Reading"),
                    ("writing", "Writing"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studymaterial",
            name="skill",
            field=models.CharField(
                blank=True,
                choices=[
                    ("speaking", "Speaking"),
                    ("listening", "Listening"),
                    ("reading", "Reading"),
                    ("writing", "Writing"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CourseBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("study_material", "Study Material"),
                            ("assignment", "Assignment"),
                        ],
                        max_length=50,
                    ),
                ),
                ("content_id", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundles",
                        to="core.course",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
