# Generated by Django 5.2.1 on 2025-06-12 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_coursebundle_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursebundle",
            options={"ordering": ["module_id"]},
        ),
        migrations.AlterModelOptions(
            name="module",
            options={"ordering": ["module_id"]},
        ),
        migrations.RenameField(
            model_name="module",
            old_name="order",
            new_name="module_id",
        ),
        migrations.AddField(
            model_name="coursebundle",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bundles",
                to="core.course",
            ),
            preserve_default=False,
        ),
    ]
