# Generated by Django 5.2.1 on 2025-06-13 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_coursebundle_options_alter_module_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursebundle",
            options={"ordering": ["module"]},
        ),
        migrations.AlterModelOptions(
            name="module",
            options={"ordering": ["order"]},
        ),
        migrations.RenameField(
            model_name="module",
            old_name="module_id",
            new_name="order",
        ),
    ]
