# Generated by Django 5.2.1 on 2025-06-13 07:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_coursebundle_options_alter_module_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursebundle",
            options={"ordering": ["module_id"]},
        ),
    ]
