# Generated by Django 5.2.1 on 2025-06-13 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_coursebundle_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("study_material", "Study Material"),
                            ("assignment", "Assignment"),
                        ],
                        max_length=50,
                    ),
                ),
                ("content_id", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundles",
                        to="core.course",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundles",
                        to="core.module",
                    ),
                ),
            ],
            options={
                "ordering": ["module_id", "sequence"],
            },
        ),
        migrations.DeleteModel(
            name="CourseBundle",
        ),
    ]
