# Generated by Django 5.2.1 on 2025-06-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_modulebundle_delete_coursebundle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_id", models.CharField(max_length=36, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("json_content", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
